### ISSUE TITLE
vs code  volar vue2   trigger parameter hints  slots  type  any

### ISSUE THREAD

**Issue by janceChun** [vue-macros/vue-macros#199]
### Describe the bug

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/4457572/210937488-d5064574-e67f-4bb9-a444-0d530688617f.png">

vscode version: 1.74.2
volar  version: 1.0.22

[unplugin-vue-macros vue2](https://github.com/sxzz/unplugin-vue-macros/tree/main/playground/vue2)  trigger parameter hints  slots  type   any  

### Reproduction

trigger parameter hints  fail in vs code plugin volar  for vue2  slots  type 

### System Info

```Shell
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://vue-macros.sxzz.moe/macros/define-slots.html
It's a known issue, because Volar does not support it yet.

**Comment by sxzz** [comment]
Since Vue 2 is already EOL, it seems we have no way to support it. However, we have also launched a paid plan. #373
