### ISSUE TITLE
$defineModels not working as expected

### ISSUE THREAD

**Issue by adroslice** [vue-macros/vue-macros#292]
### Describe the bug

After discovering this as an alternative for the deprecated Vue3 Reactivity Transforms, I had a read through the docs and saw this really cool defineModel macro, which could vastly simplify passing around some reactive state.
However, the version mentioned [here](https://vue-macros.sxzz.moe/macros/define-model.html#with-reactivity-transform) does not allow me to use the resulting variable as a v-model in the template, because there it only counts as a non-writable prop, resulting in the following error:
"[plugin:vite:vue] v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead."
This is less of a bug and more a natural result of how the feature is implemented, however the way it limits its use is certainly unintended. I invite further discussion in the matter and apologize if my issue has been poorly expressed, since it has been a while since I've used Vue at all.

Btw, the output of envinfo seems to be wrong - Firefox (110.0) is my main browser after all.

### Reproduction

https://github.com/adroslice/vue-macros-definemodel-repro/tree/main/client

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz
    Memory: 16.08 GB / 31.96 GB
  Binaries:
    Node: 18.6.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 8.13.2 - ~\AppData\Local\pnpm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
`$defineModel` is not stable now, you can try `defineModel`.

**Comment by sxzz** [comment]
According to [docs](https://vue-macros.sxzz.moe/macros/define-model.html#with-reactivity-transform)
> Assignment expression is only supported in `<script setup>` block. In other words invalid in `<template>`.

`v-model` is a syntax sugar of assigning value, so not supported now.
