### ISSUE TITLE
[Bug] SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy".

### ISSUE THREAD

**Issue by wenfangdu** [vue-macros/vue-macros#314]
[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/vue-macros)

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/28700378/226612434-02bfd228-aa1d-492b-96f2-df2a8f01bebd.png">

1. `pnpm dev`
2. Open and refresh the webpage

**Comment by sxzz** [comment]
Fixed in `unplugin-vue-macros@1.10.2`
