### ISSUE TITLE
✨ Allow using `defineSlots` short syntax in Vue 3.3

### ISSUE THREAD

**Issue by jd-solanki** [vue-macros/vue-macros#363]
### Clear and concise description of the problem

Hi 👋🏻 

I'm fan of DX you bring to the vue ecosystem. Recently I upgraded to vue 3.3 and wanted to use defineSlots' short syntax but unfortunetly due to volar's limitation this isn't provided officially. However, I noticed Vue Macros still provides support for the short syntax if docs are up to date.

Problem I'm facing is described in volar's issue [here](https://github.com/vuejs/language-tools/issues/3117#issuecomment-1537498659).

Additionally, I wanted to ask does Vue Macros support compex types like `Record` for defineSlots? I'm using generic components feature and want to generate slots based on object like [this](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/components/table/meta.ts#L65-L67).

### Suggested solution

Enable shortcut syntax and complex type support along with volar support for Vue 3.3

### Alternative

None

### Additional context

Ref: https://github.com/vuejs/language-tools/issues/3141

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jd-solanki** [comment]
Hey,

Thanks for the quick response.

> _you want Vue 3.3 (Vue core) to support shortcut syntax for defineSlots, right_

Yes, but I know it isn't support ATM and there's open issue for this in volar: https://github.com/vuejs/language-tools/issues/3117

The point I'm trying to make is, `defineSlots` short syntax doesn't work for projects using vue 3.3+. Additionally, you already mentioned that this macro is disable for vue 3.3 here: https://vue-macros.sxzz.moe/macros/define-slots.html

That means if someone who is using vue 3.3, he/she won't able to use `defineSlots` short syntax.

Here's reproduction: https://github.com/jd-solanki/volar-vue-playground/blob/vue-macros-short-defineSlots/src/foo/Foo.vue

> **Note**
> Watch our for branch

I hope I made my point.

## Additional Context

1. Aren't you at london ATM?
2. (Just a friendly question) I'm on the verge of the release for anu and can't figure out why I'm getting error `Type '{}' has no call signatures` in `src/bar/Bar.vue` slots. Let me know if you know the reason. I mentioned more details in issue I referenced above.

Thanks.

Happy coding 🙌🏻

**Comment by sxzz** [comment]
Hi, sorry for so long delay reply.

`defineSlots` is disabled in Vue 3.3, because Vue 3.3 will remove it in runtime, so it's unnecessary to transform in Vue Macros.

Currently, Volar don't support the short syntax of `defineSlots`, we can use `@vue-macros/volar/define-slots` for support.

It's worth mention that `defineSlots` is only designed for Volar (type system), for runtime, both Vue Macros and Vue 3.3 will just remove `defineSlots` macro only. The only difference between Vue Macros and the official version is Volar plugin.
