### ISSUE TITLE
booleanProp break in @vue-macros/nuxt

### ISSUE THREAD

**Issue by Mohamadhassan98** [vue-macros/vue-macros#442]
I have a nuxt-3 project and I've recently updated my `@vue-macros/nuxt` package to latest version (1.5.0).
Now the static boolean prop passing (Or whatever it's named) doesn't work as expected.

before:
```html
<MyComponent prop />
```
was translated to
```html
<MyComponent :prop="true" />
```
which is vue's default behaviour.

But now it's translated to `false` somehow.

I've noticed that you have a macro named `booleanProp` which is enabled by default, that does the same vue's default behavior.
I'm not sure if I missed something or misconfigured my project anyhow, but I'd disabled the macro and the problem is solved, the static prop passing is translated to `true` value as before.

I'm not sure what was the motivation behind implementing the macro in the first place, there is no further information in the documentation about the actual usage or motivation. Whatever that is, it's broken. And it seems that it should not be enabled by default.

**Comment by sxzz** [comment]
This feature is disabled by default now. Sorry for the issue.
