### ISSUE TITLE
When using pug lang in templates data state get's wiped out when updating a .vue Single File Component with Reactivity Transform

### ISSUE THREAD

**Issue by JordashTalon** [vue-macros/vue-macros#455]
Having a strange issue when using pug with reactivity transform macro.

If you have a simple template like this:

```
<template lang="pug">
.pageWrapper
  p Variable should show here: #[b {{value}}]
  p Change text here to something else
</template>

<script setup>
let value = $ref('Value here');
</script>
```

And a nuxt.config.ts like this:
```
import ReactivityTransform from '@vue-macros/reactivity-transform/vite';

export default defineNuxtConfig({
  vite: {
    plugins: [ReactivityTransform()],
  },
  devtools: { enabled: true },
});
```

First time you load the page it renders perfectly fine.  But if you change the template then it seems to wipe out the data. See screenshots below:

![image](https://github.com/vue-macros/vue-macros/assets/957100/a542ba7b-c621-4b02-81d8-e56167899285)

If you change the template the data disappears during hot module reload:

![image](https://github.com/vue-macros/vue-macros/assets/957100/b0e7fdc9-749e-41ff-b6e6-30ba512b5537)

Any ideas on a fix for this? It works fine without using Pug, but we use Pug extensively for development.

One side note, before using the Vue Macro we used reactivity transform like this:
```
export default defineNuxtConfig({
  vite: {
    vue: {
     reactivityTransform: true
   }
  }
});
```
And it worked fine, but Vue is removing that way of using Reactivity Transform.

Here is a minimum reproducible project:
https://stackblitz.com/edit/github-17oxys?file=pages%2Findex.vue

**Comment by sxzz** [comment]
The bug is because of `@vitejs/plugin-vue`. Trying to fix it.

**Comment by JordashTalon** [comment]
> The bug is because of `@vitejs/plugin-vue`. Trying to fix it.

Thanks a ton!

**Comment by sxzz** [comment]
Let's track https://github.com/vitejs/vite-plugin-vue/pull/227

**Comment by so1ve** [comment]
Out of topic: @JordashTalon There is an official nuxt integration for vue-macros so you don't have to setup the vite plugin manually

**Comment by JordashTalon** [comment]
@so1ve I think my example is using the official nuxt integration for Vue-macros? Or am I implementing it wrong?

**Comment by so1ve** [comment]
Ah! I see, you are using a separate package, not the whole vue-marcos

**Comment by JordashTalon** [comment]
I'll try it with the nuxt vue macros integration, I wonder if that will fix it?

**Comment by JordashTalon** [comment]
I tested the nuxt integration docs from here: https://vue-macros.sxzz.moe/guide/nuxt-integration.html 

Unfortunately that does not solve the problem :'(

**Comment by sxzz** [comment]
Fixed, please upgrade to `@vitejs/plugin-vue@4.3.2`.

**Comment by JordashTalon** [comment]
@sxzz If i'm using the Reactivity Transform Macro here: https://vue-macros.sxzz.moe/features/reactivity-transform.html how would I upgrade the vitejs plugin? I think it's added as a dependency to that module? Or should I manually install 4.3.2 as a new dependency?

**Comment by JordashTalon** [comment]
Actually it worked! I just did `npm install @vitejs/plugin-vue@4.3.2` and it started working perfectly, thanks!

I'm wondering if the modules listed on these pages:
https://vue-macros.sxzz.moe/features/reactivity-transform.html
https://vue-macros.sxzz.moe/guide/nuxt-integration.html

Should be updated to automatically use that version of plugin-vue ?

**Comment by sxzz** [comment]
I'm not familiar to npm itself (I'm using pnpm). Since you're using Nuxt with Vite integration and it's unrelated to Vue Macros. So I don't think writing down into Vue Macros docs is suitable. Maybe `npm upgrade @vitejs/plugin-vue` could be helpful, instead of installing a new dep.
