### ISSUE TITLE
打包项目的时候报错，unplugin-vue-macros：2.4.10

### ISSUE THREAD

**Issue by Xdy1579883916** [vue-macros/vue-macros#479]
> [unplugin-vue-define-prop] The first argument of defineProp must be a literal string. (kevinEdition)

**Comment by Xdy1579883916** [comment]
![image](https://github.com/vue-macros/vue-macros/assets/40905802/890cdcc5-760d-48ef-a898-3d46be353304)
我没有用到这个define-prop的功能，不知道为什么会报错，所以没有贴的很详细

**Comment by Xdy1579883916** [comment]
我vite项目中是这样配置的

![image](https://github.com/vue-macros/vue-macros/assets/40905802/c9ed76a2-22be-4d67-9539-800f2c74293e)

**Comment by Xdy1579883916** [comment]
由于我并没有用到 defineProp功能，我可以暂时选择关闭它来解决我的报错，希望你们可以找到错误原因

![image](https://github.com/vue-macros/vue-macros/assets/40905802/111790eb-eb09-4388-88f6-8889e7cde809)

**Comment by zhiyuanzmj** [comment]
sorry, I wrote this bug yesterday #476
