### ISSUE TITLE
Vue marcro plugin breaks the vitest running

### ISSUE THREAD

**Issue by Diboby** [vue-macros/vue-macros#490]
### Describe the bug

Hello,

When I add the marcro plugin into my vitest config file, all tests failed with the error `Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.`

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-6jwltw?file=vite.config.ts,test%2Fconfig%2Fvitest.setup.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.66 GB / 15.26 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v16.19.1/bin/pnpm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 116.0.5845.96
  npmPackages:
    vitest: ^0.34.2 => 0.34.3
```

### Used Package Manager

npm

**Comment by sxzz** [comment]
`setupSFC` feature will treat all `xxx.setup.ts` as a Vue SFC, including `vitest.setup.ts`. We can rename `vitest.setup.ts` to another name, avoiding name conflicts. Or add `exclude` option into `vite.config.ts`
```
setupSFC: {
  exclude: [/vitest\.setup\.ts/],
},
```

**Comment by Diboby** [comment]
Only the rename works for me. Thank you !

**Comment by sxzz** [comment]
In the next release, excluding vitest setup files will be the default behavior.
