### ISSUE TITLE
Warning: Cannot find Vue plugin (@vitejs/plugin-vue or unplugin-vue). Please make sure to add it before using Vue Macros

### ISSUE THREAD

**Issue by aboutZZ** [vue-macros/vue-macros#504]
After upgrading `unplugin-vue-macros` from `1.7.3`  to `2.5.1`, a warning shows up when I run the vite project.

```
pnpm.cmd run serve

08:43:00 [vite] warning: Cannot find Vue plugin (@vitejs/plugin-vue or unplugin-vue). Please make sure to add it before using Vue Macros.
  Plugin: unplugin-vue-short-vmodel

  VITE v4.4.9  ready in 3079 ms

  ➜  Local:   http://localhost:8848/    
  ➜  Network: http://192.168.1.5:8848/  
  ➜  press h to show help
```

```ts
// vite.config.ts
import vue from "@vitejs/plugin-vue";

VueMacros({
  plugins: {
    vue: vue(),
    // jsx、tsx语法支持
    vueJsx: VueJsx(),
  },
}),
```
There is a `@vitejs/plugin-vue` plugin, but `vue-macros` didn't dected it

**Comment by sxzz** [comment]
Could you please provide a reproduction repo?

**Comment by aboutZZ** [comment]
I tested on [stackblitz ](https://stackblitz.com/edit/vitejs-vite-r1pts7)but the waning message didn't show up. So I made a simple project to reproduce, see attachment below.
I'm using `pnpm`.

[vue-macros-#504-reproduce.zip](https://github.com/vue-macros/vue-macros/files/12602870/vue-macros-.504-reproduce.zip)


![图片](https://github.com/vue-macros/vue-macros/assets/15063761/9d42c630-beac-438e-acc5-35741291470a)

**Comment by sxzz** [comment]
Still cannot reproduce. Try to `pnpm upgrade` or upload your lockfile in the repo.

**Comment by aboutZZ** [comment]
Update `@vitejs/plugin-vue` up to `4.3.4` solve the issue.
