### ISSUE TITLE
"Could not resolve id" on Nuxt after upgrading from 3.6.5 to 3.7.x

### ISSUE THREAD

**Issue by nikowonde** [vue-macros/vue-macros#505]
I'm facing a problem that seems to be related to '@vue-macros/nuxt' after upgrading to 3.7.x.

Reproduction, starting project in dev mode with 'npm run dev' it should throw two warnings:
`[nuxt] Could not resolve id ../types/common /home/projects/nuxt-starter-itrzr5/components/Test.vue`
`[nuxt] Could not resolve id ../jsx /home/projects/nuxt-starter-itrzr5/node_modules/vue/dist/vue.d.ts`

These warnings seems to go away after disabling '@vue-macros/nuxt' module in nuxt config.

https://stackblitz.com/edit/nuxt-starter-itrzr5?file=nuxt.config.ts

Side note:
Changing types/common.d.ts to types/common.ts in repro seems to clear first message of those two, leaving only message about `...jsx`

**Comment by sxzz** [comment]
It won't break anything now, because it's a just warning. You can disable `betterDefine` feature if you don't need it.

**Comment by nikowonde** [comment]
> It won't break anything now, because it's a just warning. You can disable `betterDefine` feature if you don't need it.
> 
> ```ts
> export default defineNuxtConfig({
>   modules: ['@vue-macros/nuxt'],
>   macros: {
>     betterDefine: false,
>   },
> })
> ```
> 
> P.S You need to install `typescript` as a dep, due to design of nuxt.

Thanks for the info, disabling betterDefine seems to do the trick! I'll close this.

**Comment by kylegl** [comment]
I upgraded nuxt and this took me forever to track down. I think we should add to the docs?
