### ISSUE TITLE
Property 'name' is missing in type 'Plugin<any>[]' but required in type 'Plugin<any>'

### ISSUE THREAD

**Issue by lixiaofa** [vue-macros/vue-macros#530]
### Describe the bug

在rollup 中配置VueMacros报错：
![image](https://github.com/vue-macros/vue-macros/assets/23230215/31584749-a01f-48c2-b1d8-83511e676851)

### Reproduction

https://github.com/element-plus/element-plus/blob/dev/internal/build/src/tasks/full-bundle.ts

### System Info

```Shell
node: v18.16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
预期行为，可以在 Element Plus 中修复。请到 Element Plus repo 提 issue。

**Comment by lixiaofa** [comment]
大佬，已经提了，能帮忙看看吗



---- 回复的原邮件 ----
| 发件人 | 三咲智子 Kevin ***@***.***> |
| 日期 | 2023年10月19日 14:35 |
| 收件人 | ***@***.***> |
| 抄送至 | Sima ***@***.***>***@***.***> |
| 主题 | Re: [vue-macros/vue-macros] Property 'name' is missing in type 'Plugin<any>[]' but required in type 'Plugin<any>' (Issue #530) |

预期行为，可以在 Element Plus 中修复。请到 Element Plus repo 提 issue。
