### ISSUE TITLE
setupSFC error: Illegal tag name. Use '&lt;' to print '<'.

### ISSUE THREAD

**Issue by gastrodia** [vue-macros/vue-macros#541]
### Describe the bug

Versions after 2.2.0 setupSFC reports an error.

![image](https://github.com/vue-macros/vue-macros/assets/96605737/40c16297-b951-484b-ba1f-74665fe350de)

![image](https://github.com/vue-macros/vue-macros/assets/96605737/b590d705-67a4-4976-82f3-34ca71e50f7d)

![image](https://github.com/vue-macros/vue-macros/assets/96605737/88997622-0b17-412a-9e69-535f644a604f)

At first I was using version 2.2.0 in my project and after updating the version I got this error. I reproduced the error in Reproduction.

![image](https://github.com/vue-macros/vue-macros/assets/96605737/6b1761dc-7355-4732-8821-a6d3faca38e9)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vmyu6o?file=src%2Fcomponents%2Fhello.setup.tsx

### System Info

```Shell
unplugin-vue-macros > 2.2.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
setupSFC is disabled by default now. Please enable it manually
