### ISSUE TITLE
Support conditional properties

### ISSUE THREAD

**Issue by manniL** [vue-macros/vue-macros#546]
### Clear and concise description of the problem

Imagining a component `SomeComponent.vue`:

```vue
<script setup lang="ts">
const props = defineProps<{ one: string } | { other: number }>()
</script>

<template>
    <pre>{{ props }}</pre>
</template>
```

If we use it right now, we don't get any type errors when providing `one` *and* `another` - though these are mutually exclusive props based on the TS definition

### Suggested solution

Give type errors when using both props together 🤔
Maybe `defineProps` could be adapted to facilitate that?

```vue
<script setup lang="ts">
import SomeComponent from './SomeComponent.vue';
</script>

<template>
  <!-- This should not work -->
  <SomeComponent :one="'This should not work'" :other="42" />
  <SomeComponent one="This should not work either" :other="42" />

  <!-- This is fine -->
  <SomeComponent :one="'This is fine'" />
  <SomeComponent :other="42" />
</template>
```

### Alternative

"Providing" this in core https://github.com/vuejs/core/issues/8952

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
This is an enhancement or bug that needs Vue core to fix. If there's a PR in vue core, I'll push it to be merged in Vue core.

**Comment by manniL** [comment]
@sxzz Do you have any thoughts or ideas regarding a possible implementation? 🤔
e.g. should it be on a TS-only level or should there also be an abstraction on the "vue-style" props level?

**Comment by sxzz** [comment]
It should be on a TS-only level. The types of Vue component is too complex now, and I have no idea to solve it.

**Comment by manniL** [comment]
Alright, thanks a lot for your time and your input 👍🏻
