### ISSUE TITLE
unplugin-vue-macros 引入的 unplugin-vue-define-options/vue2-macros-global 报错

### ISSUE THREAD

**Issue by lx11573** [vue-macros/vue-macros#557]
### Describe the bug

Vue2 中使用 unplugin-vue-macros 时，引入的 unplugin-vue-define-options包中，没有 vue2-macros-global

![image](https://github.com/vue-macros/vue-macros/assets/12030247/d9abd391-7535-4e08-8042-ee264795c3c0)

### Reproduction

https://www.npmjs.com/package/unplugin-vue-define-options/v/1.3.18?activeTab=code

### System Info

```Shell
OS 10.15.7
Node 16.17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
For those without `vue2-macros-global`, you can use `macros-global` directly.
对于没有 `vue2-macros-global` 的，可以直接使用 `macros-global`

This will be noted later in the documentation
稍后会在文档中注明这一点
