### ISSUE TITLE
使用 defineModels 的时候应当和直接声明保持一致，是否能详细说明一下 passive 的意义

### ISSUE THREAD

**Issue by zhengyimeng** [vue-macros/vue-macros#565]
### Describe the bug

```vue
# App.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import HelloWorld from "./components/HelloWorld.vue";

const msg = ref({ name: 123, label: 789 });
const msg2 = ref({ name: 65, label: 456 });

watch([msg, msg2], () => {
  console.log(1);
});

[msg.value, msg2.value] = [msg2.value, msg.value];
</script>

<template>
  <HelloWorld v-model:msg="msg" v-model:msg2="msg2" />
</template>
```
// HelloWorld.vue
```vue
<script setup lang="ts">
let { msg, msg2 } = defineModels<{
  msg: number;
  msg2: number;
}>();

const onClick = () => {
  [msg2.value, msg.value] = [msg.value, msg2.value];
};
</script>

<template>
  <button @click="onClick()">adsfsdf</button>
</template>
```

第一次的交换，watch 只会监听到一次
当执行 HellowWorld 里的onClick 时，watch 会监听到两次

 // 文档
<img width="669" alt="image" src="https://github.com/vue-macros/vue-macros/assets/20783425/7c445c70-3b6a-4d12-8928-bb6427759697">
我试了一下，如果编译后是这样的话，watch 监听到也是一次
所以到底是哪里出错了

### Reproduction

https://github.com/zhengyimeng/test-defineModels.git

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 180.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 4.0.0 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.10.2 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
    bun: 0.1.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
`passive` 与 VueUse 的 [useVModel](https://vueuse.org/core/useVModel/) 用途一致。 https://vueuse.org/core/useVModel/#type-declarations

`passive` is used in the same way as [useVModel](https://vueuse.org/core/useVModel/) from VueUse. https://vueuse.org/core/useVModel/#type-declarations

**Comment by sxzz** [comment]
`defineModels` 底层用的是 VueUse 的 [useVModel](https://vueuse.org/core/useVModel/)，行为与 emit 有些许不一致。
`defineModels` uses VueUse's [useVModel](https://vueuse.org/core/useVModel/) at its core, and its behavior is slightly different from `emit`.

你的截图来自 `$defineModels` 的编译结果。
Your screenshot comes from the compilation result of `$defineModels`.

**Comment by Eacolt** [comment]
使用javascript怎么用defineModels?

**Comment by sxzz** [comment]
`defineModels` 不支持在 JS 下使用。
