### ISSUE TITLE
defineModel触发事件问题

### ISSUE THREAD

**Issue by andyyxw** [vue-macros/vue-macros#618]
### Describe the bug

```vue
/** Parent.vue **/
<script setup>
  <MyComponent
    v-model="value"
    v-model:title="title"
  />
</script>

/** MyComponent.vue **/
<script setup>
  const title = defineModel('title')
</script>
<template>
  <input type="text" v-model="title" />
</template>
```
@sxzz 当组件有多个 `v-model`，使用带名称的 `defineModel` 时，会额外触发父组件的 `update:modelValue` 事件 导致 `value` 更新，这个是期望行为吗？
还是说这种用法有问题，有多个v-model时 每个都必须带上参数名?

### Reproduction

https://play.vuejs.org/#eNqNU01vm0AQ/SurvdiWDKvIOSFsua1yaKW0VdsjFwpje1PYXe0HcYT4751dDMHUjXKCmTfz5s0baOkHpeLGAU1oagrNlSUGrFO7TPBaSW1JSzQcSEcOWtZkgaWLEXp8+STxTYCwFzhmk5znxeJMFFIYS5q8ckC2nm65CMFiNWCW22rEQuCxlPWSUAwGFmpV5RYwIiQ93e0CR0La9kLddSnD9ABjvqed5ifyfExIE9WyhGqb0UCS0at0EhgQDM8B3DtVopAklEShD0uWzYpsd8QvJCuIK3lcLi6F/bZr0qzmFAP/G829Ha/NDDdJ2egGXdOZ5zduee1yCQcu4NGrf6fbXCiH/S8qeAFnm9GJcxdzbiizBicf+DF+MlKgrtazZbRAubwC/U1ZjsoyilfsfcloXlXy+UvIWe1gPeSLExR/buSfzNnnMvpdgwHdoJARs7k+Amr18MPPr0H3CKJ652W/Af4AvIbzGvuyj06UKHtSF9R+Dr8DF8df5uFsQZhhKS/UV3ahHj8xB/5S/1v9Ve4m3oS+THToYv+7RXWuZj72wDUJzujFnqxVJmGsKAW24aV4o2MBlglVsz2WMe2E5TVEpaz3m/g+vrtnJTd2mo/B1NFvLZ/RWmSZbO4Jgt860iBK0N6X982dtV3NnmH/zB9t6f4CN7uaIA==

### System Info

```Shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Memory: 2.55 GB / 15.84 GB
Binaries:
  Node: 18.18.2 - ~\AppData\Local\nvs\default\node.EXE
  Yarn: 1.22.19 - ~\.npm-global\yarn.CMD
  npm: 9.8.1 - ~\.npm-global\npm.CMD
  pnpm: 8.14.0 - ~\.npm-global\pnpm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.133)
  Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Expected behavior, since MyComponent.vue does not declare `modelValue` in props/emis, it will be passed to its child element, which is the `input` element

预期的行为，因为 MyComponent.vue 并没有在 props/emits 声明 `modelValue`，它会传递到它的子元素，即 `input` 元素
