### ISSUE TITLE
defineSlots: use Short Syntax in vscode(Volar2+), template slot type is never.

### ISSUE THREAD

**Issue by warmthsea** [vue-macros/vue-macros#639]
### Describe the bug

https://vue-macros.dev/macros/define-slots.html

<hr />

**Short Syntax：template slot type is never.**

![image](https://github.com/vue-macros/vue-macros/assets/45450994/c1336613-38e7-4ce6-a7e5-3628eee5da06)

<hr />

**Full Syntax (Official Version):  type is string, normal.**

![image](https://github.com/vue-macros/vue-macros/assets/45450994/75709d54-0fb6-41ca-b913-2a82f4378fad)

<hr />

![image](https://github.com/vue-macros/vue-macros/assets/45450994/c7436bdc-9c97-4818-8364-254bcf8990fa)

 tsconfig.json vueCompilerOptions add "target 3", template error, see gif ↓

![screenshots](https://github.com/vue-macros/vue-macros/assets/45450994/f207211e-3b4d-4950-9bca-b92bd34ba5b2)

### Reproduction

https://github.com/warmthsea/test-volar2--defineSlots?tab=readme-ov-file

### System Info

```Shell
vscode: version last
volar(Vue-Official): v2.0.6

@vue-macros/volar: "^0.18.11",
"unplugin-vue-macros": "^2.7.10",

<hr />

System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 13.47 GB / 31.70 GB
  Binaries:
    Node: 18.17.0 - R:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - R:\nodejs\npm.CMD
    pnpm: 8.15.4 - W:\warmthsea\test-volar2--defineSlots\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by warmthsea** [comment]
https://github.com/vuejs/language-tools/issues/3955

**Comment by sxzz** [comment]
As docs mentioned https://vue-macros.dev/guide/getting-started.html
> ❌ Considering that v2 is not yet stable and some issues remain unresolved, plus adapting to 2.x would mean an almost irreversible upgrade for Vue Macros, we've decided not to support 2.x at this time. In other words, we will continue to support v1.

**Comment by warmthsea** [comment]
Thank you for your reply. It seems that I need to change the abbreviation in the project to the official one.
