### ISSUE TITLE
Is it possible to provide macros for vue2.7 that are only aligned to vue3 via Vue Macros

### ISSUE THREAD

**Issue by curlykay** [vue-macros/vue-macros#657]
### Clear and concise description of the problem

I know that functionally the answer is YES. but I ran into some DX issues in my attempts.
The macros required to align vue2.7 to vue3 are 'defineOptions','defineModel','defineSlots'
<img width="873" alt="image" src="https://github.com/vue-macros/vue-macros/assets/35558285/4cc6f9a1-99d7-43f2-953b-075c127f0ab0">
1. Can't filter IntelliSense in vscode.
   Some macros (e.g. :defineModels) are turned off on the `vue.config.js` ,`tsconfig.json`configuration, but due to the use of "unplugin-vue-macros/vue2-macros-global",vscode IntelliSense will still prompt.
``` javascript
const { defineConfig } = require('@vue/cli-service');
const VueMacros = require('unplugin-vue-macros/webpack');
module.exports = defineConfig({
  transpileDependencies: true,
  parallel: false,
  configureWebpack: {
    plugins: [
      VueMacros({
        // defineOptions: Options$6,
        // defineProps: Options$8,
        // defineSlots: Options$b,
        betterDefine: false,
        booleanProp: false,
        chainCall: false,
        defineEmit: false,
        defineModels: false,
        defineProp: false,
        definePropsRefs: false,
        defineRender: false,
        exportExpose: false,
        exportProps: false,
        exportRender: false,
        hoistStatic: false,
        jsxDirective: false,
        namedTemplate: false,
        reactivityTransform: false,
        setupBlock: false,
        setupComponent: false,
        setupSFC: false,
        shortBind: false,
        shortEmits: false,
        shortVmodel: false,
      }),
    ],
  },
});
```
<img width="541" alt="image" src="https://github.com/vue-macros/vue-macros/assets/35558285/c10a60b1-8837-42fb-83aa-6494ecbc0111">

<img width="592" alt="image" src="https://github.com/vue-macros/vue-macros/assets/35558285/2172f7f9-defe-4a59-9dc5-253bc4ad8a77">

I'm guessing that using 'unplugin-vue-macros/vue2-macros-global' with custom cropping solves the problem
 
2. Missing macro 'defineModel' that was added in vue 3.4.
     ps：Forgive me, this point is probably more appropriate as a separate issue.
<img width="517" alt="image" src="https://github.com/vue-macros/vue-macros/assets/35558285/066780d0-d10a-43ec-9622-2a3f2c6f3f18">

  
env
vscode 1.8.8
volar 1.8.7(takeover)
macos 14.4.1

repo:https://github.com/curlykay/vue2-macros-vuecli

### Suggested solution

How do I configure Vue Macros to make vue2.7 align with vue3 in the dimension of macros? I'd be happy to learn.

Or

Just like the standalone 'unplugin-vue-define-options', would it be possible to provide a standalone 'unplugin-vue-macros-compat' and '@vue-macros-compat/volar' aligned with vue3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
1. For the first question, you can copy the content from https://github.com/vue-macros/vue-macros/blob/main/packages/macros/vue2-macros-global.d.ts and delete the macros you don't need. Due to TS limitations, it's difficult to provide type support based on configuration (maybe future Volar plugins can help).

3. `defineModels` is a superset of `defineModel`, so you can use `defineModels` instead for now. If you really need `defineModel`, it is recommended to create a new issue and wait for more demand (or wait for a PR).

**Comment by curlykay** [comment]
I'll give it a go.
And thanks for the effort you put into this project, which makes it possible for people like me, who are temporarily stuck in vue2 for various reasons, to enjoy a relatively complete vue3 DX.
