### ISSUE TITLE
when defineRender and unplugin-vue-components work toghter. it like this 

### ISSUE THREAD

**Issue by chenxi24** [vue-macros/vue-macros#681]
### Describe the bug

![image](https://github.com/vue-macros/vue-macros/assets/40349890/a38d6dfc-1cee-424f-8a86-66cb04ad5e66)

it work but vs code throw error

### Reproduction

in isuess

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 1.25 GB / 7.89 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
You need to import `Header` from other files. For usage of JSX, refer to https://github.com/vuejs/babel-plugin-jsx
