### ISSUE TITLE
betterDefine breaks SFC style v-bind working on production build (in vue 2.7)

### ISSUE THREAD

**Issue by serialine** [vue-macros/vue-macros#686]
### Describe the bug

When betterDefine flag on
production build of SFC's style v-bind syntax does not work.

https://stackblitz.com/edit/github-awz8ye-pgy7dv?file=nuxt.config.ts,components%2FGridLayout.vue

`GridLayout.vue`
```vue
<script setup lang="ts">
const props = withDefaults(defineProps<{ slice?: number }>(), { slice: 3 });
</script>

<template>
  <div class="grid">
    <div v-for="i in 20" class="column">I am Grid!</div>
  </div>
</template>

<style scoped lang="scss">
.grid {
  display: grid;
  column-gap: 8px;
  grid-template-columns: repeat(v-bind('props.slice'), minmax(0, 1fr));
}

.column {
  border: 1px solid black;
}
</style>
```

```vue
<script setup lang="ts">
import GridLayout from '../components/GridLayout.vue';

const column = ref(4);
</script>

<template>
  <div>
    <GridLayout :slice="column" />
    columns: <input type="number" v-model.number="column" />
  </div>
</template>
```

`npm run build && npm run start`

Expects: GridLayout works with input value interaction

### Reproduction

https://stackblitz.com/edit/github-awz8ye-pgy7dv?file=nuxt.config.ts,components%2FGridLayout.vue

### System Info

```Shell
❯ npx envinfo --system --binaries --browsers
Need to install the following packages:
envinfo@7.13.0
 

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by serialine** [comment]
[genNormalScriptCssVarsCode](https://github.com/vuejs/core/blob/main/packages/compiler-sfc/src/script/normalScript.ts#L32)

My company coworker hinted that it works fine when using defineComponent instead of script setup.

**Comment by sxzz** [comment]
After testing, it seems to be an issue with the upstream toolchain (`vue-loader`) in Vue 2. As long as a Vue SFC is processed (even if it's just adding a comment), it will break style `v-bind`.

Given that Vue 2 has already reached EOL, Vue Macros cannot fix this issue. However, if you still need it, you can refer to #373.
