### ISSUE TITLE
这个插件有没有办法在vitepress可以使用？

### ISSUE THREAD

**Issue by ckvv** [vue-macros/vue-macros#73]
### Clear and concise description of the problem
由于源代码使用了该插件导致，导致vitepress不能直接引用没有经过编译的组件
如果可以的话，在修改源代码后文档可以实时更新

### Suggested solution

不清楚能不能实现！

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
理论上是可以的，你可以尝试一下。

**Comment by sxzz** [comment]
你可以参考 https://github.com/element-plus/element-plus/blob/dev/docs/vite.config.ts#L72-L78
