### ISSUE TITLE
shortVmodel how to support eslint and typescript in nuxt3

### ISSUE THREAD

**Issue by pawover** [vue-macros/vue-macros#732]
i just use `pnpm dlx nuxi@latest init <project-name>` create a new project and follow the document use nuxt integration

![image](https://github.com/user-attachments/assets/33fcd3e5-a1fc-43cc-90dc-d164ebce0434)
![image](https://github.com/user-attachments/assets/9bba9291-5818-44ad-9f44-49cf9fbe614c)

`.nuxt/tsconfig.json`

![image](https://github.com/user-attachments/assets/b2e4cdf6-dc6e-4133-8de2-f85178fbbb79)

it works, but not have support for typescript and eslint in the editor

![image](https://github.com/user-attachments/assets/064fdc50-d196-4850-800b-9f05f63e9981)

any help thanks

**Comment by zhiyuanzmj** [comment]
Sorry, there is no ESLint plugin support at the moment.

**Comment by pawover** [comment]
> 抱歉，目前没有 ESLint 插件支持。

fien, maybe i can ignore the eslint warning but is there any support form volar?

**Comment by zhiyuanzmj** [comment]
Yes, We have volar plugin
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9bc4136d-6a10-4b87-8b95-f22fbe5dcd93">
