### ISSUE TITLE
Some issues with setup-sfc

### ISSUE THREAD

**Issue by subframe7536** [vue-macros/vue-macros#745]
### Describe the bug

- Fail to run setup-sfc without setting `setupSFC: { include: [/\.setup\.[cm]?[jt]sx?$/] }` in vuemarcos plugin (according to the doc).
- The imported component have wrong type definition.
  - On my local machine: 
![image](https://github.com/user-attachments/assets/11dcc2e5-1439-4952-90b4-8d50705be36c)
  - Another type issue in repro

### Reproduction

https://stackblitz.com/edit/vitejs-vite-dqqflq?file=vite.config.ts,src%2FApp.setup.tsx&terminal=dev

### System Info

```Shell
stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
You need add `@vue-macros/volar/setup-sfc` plugin to tsconfig.json
```json
{
  "vueCompilerOptions": {
    "plugins": "@vue-macros/volar/setup-sfc"
  }
}
```

**Comment by subframe7536** [comment]
Same

https://github.com/user-attachments/assets/3ff6e479-fa9f-4f38-b2f5-908719ea061b

**Comment by zhiyuanzmj** [comment]
It looks good for me.
https://github.com/zhiyuanzmj/vitejs-vite-jd6z9z

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/d62c218a-70c4-4941-891a-4806b6277d65">

**Comment by zhiyuanzmj** [comment]
And make sure your vue's vscode plugin is latest version.

**Comment by zhiyuanzmj** [comment]
By the way we have a vitesse template for setup.tsx.
https://github.com/vue-macros/template-jsx

**Comment by subframe7536** [comment]
> And make sure your vue's vscode plugin is latest version.

Thats the reason. Just remove and install the new `Vue - Official`😅

**Comment by subframe7536** [comment]
Seems that the component name is not accepted and will not auto import in vscode auto complete?


https://github.com/user-attachments/assets/dee40773-2959-45e8-b683-09d2fa3c67b0

**Comment by zhiyuanzmj** [comment]
This is a bug,  I'll fix it later.
