### ISSUE TITLE
Missing support co-usage of setupSFC and `templateRef` volar plugin

### ISSUE THREAD

**Issue by sxzz** [vue-macros/vue-macros#770]
### Describe the bug

/cc @zhiyuanzmj 

```ts
import { templateRef } from '@vueuse/core'
import Comp from './comp.setup'

const a = templateRef('test')
//    ^? Ref<any>

export default <Comp ref="test" foo={1} />
```

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
I will support tsx after this pr is merged.
https://github.com/vuejs/language-tools/pull/4644

**Comment by zhiyuanzmj** [comment]
use (jsxRef)[https://vue-macros.dev/volar/jsx-ref.html] instead.
