### ISSUE TITLE
ReferenceError: $defineProps is not defined

### ISSUE THREAD

**Issue by xalteropsx** [vue-macros/vue-macros#780]
reactivity transform work fine but $defineProps i install this "@vue-macros/define-props" but it still keep saying defineProps not define

the documentation for https://www.npmjs.com/package/@vue-macros/define-props is not proper nothing been define what to call and how to set it on vite

**Comment by sxzz** [comment]
If you're using multiple plugins, plz consider the `unplugin-vue-macros` package. See https://vue-macros.dev/guide/bundler-integration.html for details.
