### ISSUE TITLE
Object literal may only specify known properties, and 'modelValue' does not exist in type

### ISSUE THREAD

**Issue by zhiyuanzmj** [vue-macros/vue-macros#782]
### Describe the bug

Recently, my deps were auto updated and my building starting failing. I narrowed down to `vue-tsc` from `2.0.29` to `2.1.4`.

I have components that use `defineModels`. 

### Reproduction

```vue 
<script lang="ts" setup generic="T"> 
type DropdownItem = {   label: string;   value: T; };  
const { modelValue } = defineModels<{   modelValue: T; }>(); 
</script> 
```

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M3
    Memory: 71.55 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.6.0 - ~/.local/state/fnm_multishells/81365_1725202351998/bin/node
    npm: 10.8.2 - ~/.local/state/fnm_multishells/81365_1725202351998/bin/npm
    pnpm: 9.9.0 - ~/.local/state/fnm_multishells/81365_1725202351998/bin/pnpm
    bun: 1.1.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by amir20** [comment]
Is this related to https://github.com/vue-macros/vue-macros/issues/792? 

Just checking because our builds are still broken...
