### ISSUE TITLE
vue 3.5 `useTemplateRef` is transform type mistake of  `unplugin-vue-macros/volar`

### ISSUE THREAD

**Issue by Gehbt** [vue-macros/vue-macros#789]
### Describe the bug

without "plugins": ["unplugin-vue-macros/volar"]
![image](https://github.com/user-attachments/assets/846137db-e914-4939-932d-a66461dc1531)

with
![image](https://github.com/user-attachments/assets/eda42d75-fd06-40be-a40f-a5032b26ecd4)

### Reproduction

https://github.com/Gehbt/vls-bug-repro1

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 29.59 GB / 63.67 GB
  Binaries:
    Node: 20.12.2 - ~\AppData\Local\fnm_multishells\31884_1725447018920\node.EXE
    npm: 10.5.0 - ~\AppData\Local\fnm_multishells\31884_1725447018920\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Local\fnm_multishells\31884_1725447018920\pnpm.CMD
    bun: 1.1.26 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74), ChromiumDev (128.0.2677.1)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Gehbt** [comment]
unset option `useTemplateRef` could solve part of it.
![image](https://github.com/user-attachments/assets/cd878aa3-cd18-471e-aa66-ed79630b5b96)

**Comment by sxzz** [comment]
@zhiyuanzmj

**Comment by zhiyuanzmj** [comment]
Waiting for volar v2.1.6 release. and I want remove useTemplateRef and add useRef for jsx.
![image](https://github.com/user-attachments/assets/4efe8a52-d7c2-4a9b-861f-4a2b5e3a19e9)
