### ISSUE TITLE
vue 2.7 rsbuild

### ISSUE THREAD

**Issue by MinGuoGuo** [vue-macros/vue-macros#793]
### Describe the bug

vue版本 2.7，在rsbuild中引入VueMacros报错如下
<img width="776" alt="a863f627796ca93aed9a64a87" src="https://github.com/user-attachments/assets/bab3098a-d37b-4552-a37c-ad65641d23d7">

### Reproduction

none

### System Info

```Shell
mac m1pro.  
vue 2.7.16
rsbuild 0.7.2
chrome: latest
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by MinGuoGuo** [comment]
> It might be an issue with Rspack. I've reported it to their team.

thinks

**Comment by sxzz** [comment]
The version of rsbuild/rspack is too low; 1.0.1-rc.5 works correctly.
