### ISSUE TITLE
New Feature: Macros about StyleX

### ISSUE THREAD

**Issue by BeiyanYunyi** [vue-macros/vue-macros#821]
### Clear and concise description of the problem

[StyleX](https://stylexjs.com/) is a styling system developed by Meta. It's also known as an "atomic css in js at compile time" solution to styling.

For example, these code:

```vue
<script setup lang="ts">
import 'virtual:stylex.css'
</script>

<script lang="ts">
import { create, attrs } from '@stylexjs/stylex'

const styles = create({ redBold: { color: 'red', fontWeight: 'bold' } })
</script>

<template>
  <p><span :class="attrs(styles.redBold).class">Red</span> Text</p>
</template>
```

compiles to:

```css
.x1e2nbdu {
  color: red;
}
.x117nqv4 {
  font-weight: 700;
}
```

```js
const In = {},
  _o = { redBold: { color: 'x1e2nbdu', fontWeight: 'x117nqv4', $$css: !0 } },
  bo = Fi({
    __name: 'App',
    setup(e) {
      return (t, s) => (
        wl(),
        El('p', null, [
          Bs('span', { class: Wt(hs(mo)(hs(_o).redBold).class) }, 'Red', 2),
          s[0] || (s[0] = Cr(' Text'))
        ])
      )
    }
  })
```

in HTML, it looks like:

```html
<p><span class="x1e2nbdu x117nqv4">Red</span> Text</p>
```

However, the `create()` function can only be invoked in module scope, when it's in `<script setup>`, it will invoked in the `setup()` function scope, causing errors: `stylex.create() is only allowed at the root of a program.`

### Suggested solution

I'd like to write a macro like `defineStyleX`, so I can have a better DX with StyleX and Vue.

```vue
<script setup lang="ts">
import 'virtual:stylex.css'

defineStyleX({
  redBold: {
    color: 'red',
    fontWeight: 'bold'
  }
})
</script>

<template>
  <p><span v-stylex="this.$stylex.redBold">Red</span> Text</p>
</template>
```

### Alternative

[PandaCSS](https://panda-css.com/), as an alternative to StyleX, uses PostCSS to extract the class name and parse styles. Unlike StyleX, PandaCSS's function can be invoked in `setup()` scope, or even `render()` scope.

However, PandaCSS relies on PostCSS, which introduces more complexity. StyleX is a more lightweight choice since it only uses babel.

### Additional context

I'd like to make a Pull Request after discussing about the style of the solution. `v-stylex="this.$stylex.redBold"` is might not a good idea. I can also create another repository to introduce the feature, but `vue-macros` provides some handy utilities for me.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
I believe `hoistStatic` feature with magic comments is a workaround for your case. https://vue-macros.dev/features/hoist-static.html#magic-comments

**Comment by sxzz** [comment]
However, I am very happy to accept your proposal. However, `defineStyleX` can have a return value.

```vue
<script setup lang="ts">
// import automatically by vue-macros
// import 'virtual:stylex.css'

const styles = defineStyleX({
  redBold: {
    color: 'red',
    fontWeight: 'bold'
  }
})
</script>

<template>
  <p><span v-stylex="styles.redBold">Red</span> Text</p>
</template>
```
