### ISSUE TITLE
类型“ReservedProps”上不存在属性“onChangePropMessage”

### ISSUE THREAD

**Issue by 2997324154** [vue-macros/vue-macros#829]
### Describe the bug

不能将类型“{ "v-model:msg": number; onChangePropMessage: (data: number) => void; }”分配给类型“ReservedProps”。
  类型“ReservedProps”上不存在属性“onChangePropMessage”。
在一个tsx组件中引入另一个tsx组件

![Clip_2024-09-28_20-59-11](https://github.com/user-attachments/assets/d6aac91d-76f6-4ee7-9a78-8c03dae418b8)
![Clip_2024-09-28_20-59-40](https://github.com/user-attachments/assets/c62dfba0-aef6-4572-bd8e-d28edf856594)

### Reproduction

reproduction

### System Info

```Shell
{
  "name": "my-vue-1",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.2",
    "@vitejs/plugin-vue-jsx": "^4.0.1",
    "typescript": "^5.5.3",
    "unplugin-vue-macros": "^2.12.2",
    "vite": "^5.4.1",
    "vue-tsc": "^2.0.29"
  }
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 2997324154** [comment]
能够编译运行，但是ts校验报错

**Comment by sxzz** [comment]
`onChangePropMessage` is not `onChangePropMessageEmit`.
