### ISSUE TITLE
 Property "as" was accessed during render but is not defined on instance.  

### ISSUE THREAD

**Issue by amihhs** [vue-macros/vue-macros#842]
### Describe the bug

![image](https://github.com/user-attachments/assets/3f4a840e-9aeb-4fb8-b5c2-f33b2db78389)
![image](https://github.com/user-attachments/assets/60916697-3a2e-4f97-9e80-86b8199075dd)
 
Property "as" was accessed during render but is not defined on instance. 
![image](https://github.com/user-attachments/assets/64fec836-8522-46c9-8735-cc37c777cf01)

It looks like some feature of vue-macros breaks the inheritance of types, when I use @vitejs/plugin-vue directly it returns to normal
![image](https://github.com/user-attachments/assets/048c3ebd-9d72-4213-9c1d-82e1efca4e0e)

### Reproduction

https://github.com/amihhs/shadcn-vue-unocss-starter

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 18.24 GB / 31.92 GB
  Binaries:
    Node: 18.17.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 9.6.7 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Should be fixed in the latest release
