### ISSUE TITLE
Error encountered after following eslint integration setup in vue macros documentation

### ISSUE THREAD

**Issue by A-kirami** [vue-macros/vue-macros#863]
### Describe the bug

遵照官方文档的[ESLint 集成](https://vue-macros.dev/zh-CN/guide/eslint-integration.html)设置后，eslint 运行出现错误。

After following the [ESLint Integration](https://vue-macros.dev/guide/eslint-integration.html) setup in the official documentation, an error occurred when running eslint.

```
Oops! Something went wrong! :(

ESLint: 9.15.0

A config object is using the "globals" key, which is not supported in flat config system.

Flat config uses "languageOptions.globals" to define global variables for your files.

Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options

If you're not using "globals" directly (it may be coming from a plugin), please see the following:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config
```

### Reproduction

https://codesandbox.io/p/devbox/sxm83j

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.26 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
You can use `@vue-macros/eslint-config/flat` instead.

**Comment by zhiyuanzmj** [comment]
`vue-macros`'s docs is not specified. I will update it.
