### ISSUE TITLE
Custom prefix for shortVmodel not taking effect

### ISSUE THREAD

**Issue by A-kirami** [vue-macros/vue-macros#873]
### Describe the bug

Following the documentation, I configured a custom prefix for shortVmodel, but it doesn't seem to have any effect.

```json
{
  "vueCompilerOptions": {
    "plugins": ["unplugin-vue-macros/volar"],
    "vueMacros": {
      "shortVmodel": {
        "prefix": "::",
      },
    },
  },
}
```

```vue
<script setup lang="ts">
const msg1 = $ref<string>()
const msg2 = $ref<string>()
</script>

<template>
  <input $="msg1" />
  <div>{{ msg1 }}</div>
  <hr>
  <input ::="msg2" />
  <div>{{ msg2 }}</div>
</template>
```

Interestingly, `msg1` works despite the custom prefix being set to `::`, which is unexpected. Meanwhile, `msg2` does not function as intended.

### Reproduction

https://codesandbox.io/p/devbox/pjlfx5

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.83 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
You also need to configure vite.
<img width="462" alt="image" src="https://github.com/user-attachments/assets/7b4139dc-d6b4-47c2-8f01-19b2b7d38445" />

**Comment by zhiyuanzmj** [comment]
I noticed the docs don't have Vite configuration. I will add it.
