### ISSUE TITLE
使用`defineSlots`后 slots 的声明推断错误

### ISSUE THREAD

**Issue by shens3** [vue-macros/vue-macros#879]
### Describe the bug

使用 vue-tsc 生成 `.vue` 的声明文件，vue 版本为 3.2，使用到了 `defineSlots`，但是生成出来 slot 的类型为 `void`

复现步骤：
pnpm tsc

结果：
![image](https://github.com/user-attachments/assets/5a5f9fcc-a63a-41fa-a476-92c7ad5915e8)
![image](https://github.com/user-attachments/assets/a58e8c4e-0591-4b57-8945-6877588b725e)

### Reproduction

https://github.com/shens3/define-slots-demo

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 49.09 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 7.33.7 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 16.3
    Safari Technology Preview: 14.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
Sorry I can't reproduce it.
The `pnpm tsc` result is parsed when I add `jsxImportSource: "vue"` in tsconfig.app.json.
<img width="745" alt="image" src="https://github.com/user-attachments/assets/3217b990-8698-4712-a0b6-d281c901a941" />

**Comment by shens3** [comment]
> Sorry I can't reproduce it. The `pnpm tsc` result is passed when I add `jsxImportSource: "vue"` in tsconfig.app.json.
> 
> <img alt="image" width="745" src="https://private-user-images.githubusercontent.com/32807958/398615205-3217b990-8698-4712-a0b6-d281c901a941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzAzNjYsIm5iZiI6MTczNTUzMDA2NiwicGF0aCI6Ii8zMjgwNzk1OC8zOTg2MTUyMDUtMzIxN2I5OTAtODY5OC00NzEyLWEwYjYtZDI4MWM5MDFhOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAzNDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmY2ZiZWM1MzQwNDllZGMxM2Y4NTYzOGNhYTQxODk3NmVlYzBmZjNlM2M2NmJkY2JlMTg0ZDlmZWYzZDZhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zSbtiHlWWGo7Fn3z6vJvo_OTfGrq5fwSHE-nwuOIBgQ">

看起来你安装的vue版本不是3.2， 3.2 没有 jsx-runtime 呀，我加了这个配置都找不到，安装依赖的时候使用 pnpm i --frozen-lockfile，不然vue 会升级到最新版本了
![image](https://github.com/user-attachments/assets/0433002e-bacf-4df9-82fd-41cf478518c4)

**Comment by zhiyuanzmj** [comment]
哦哦 我知道了 vue-macros 里的 defineSlots 类型返回的是 void 我把它改成返回范型就好了
https://github.com/vue-macros/vue-macros/blob/main/packages/define-slots/macros-global.d.ts#L2

**Comment by shens3** [comment]
> 哦哦 我知道了 vue-macros 里的 defineSlots 类型返回的是 void 我把它改成返回范型就好了 https://github.com/vue-macros/vue-macros/blob/main/packages/define-slots/macros-global.d.ts#L2

谢谢~ 想问问什么时候可以发布呀？发布的合并好像还卡在测试报告？

**Comment by zhiyuanzmj** [comment]
哦哦 忘记发布了

**Comment by zhiyuanzmj** [comment]
哦哦 忘记发布了 那我现在发一版吧
